apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: che-vsx-dev-image
  namespace: che-dev-images
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: che-vsx-dev-image
  namespace: che-dev-images
spec:
  source:
    git:
      uri: https://github.com/cgruver/che-openvsx-registry.git
      ref: main
    contextDir: "workspace-config"
  strategy:
    dockerStrategy:
      dockerfilePath: "./Containerfile"
  output:
    to:
      kind: ImageStreamTag
      name: che-vsx-dev-image:latest
